# Generated by Django 3.2.23 on 2024-01-08 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot_librenms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LibreNMSInstance",
        ),
    ]
