# Generated by Django 3.1.13 on 2021-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_ssot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sync",
            name="diff_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="load_time_source",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="load_time_target",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="memory_peak",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="memory_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="memory_usage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="sync_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
