# Generated by Django 3.1.12 on 2021-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_ssot", "0002_refinements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclogentry",
            name="object_repr",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
    ]
