# Generated by Django 3.2.18 on 2023-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0003_alter_synclogentry_textfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sync",
            name="summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
