# Generated by Django 3.2.16 on 2023-05-23 20:05

from django.db import migrations, models
import nautobot_ssot.models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0004_sync_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sync",
            name="diff",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="compressed_diff",
            field=nautobot_ssot.models.CompressedJSONField(blank=True, default=dict),
        ),
    ]
