# Generated by Django 3.2.16 on 2023-05-23 20:05

from django.db import migrations
import nautobot_ssot.models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0004_sync_summary"),
    ]

    operations = [
        migrations.RenameField(model_name="sync", old_name="diff", new_name="json_diff"),
        migrations.AddField(
            model_name="sync",
            name="diff",
            field=nautobot_ssot.models.CompressedJSONField(blank=True, default=dict),
        ),
    ]
