# Generated by Django 3.2.16 on 2023-07-03 18:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0004_sync_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sync",
            name="diff",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name="synclogentry",
            name="diff",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
