# Generated by Django 3.2.16 on 2023-05-23 20:05

from django.db import migrations, models
import nautobot_ssot.models


def copy_diff_to_compressed_diff(apps, schema_editor):
    for sync in nautobot_ssot.models.Sync.objects.all():
        sync.compressed_diff = sync.diff
        sync.validated_save()


def undo_diff_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0004_sync_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sync",
            name="diff",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sync",
            name="compressed_diff",
            field=nautobot_ssot.models.CompressedJSONField(blank=True, default=dict),
        ),
        migrations.RunPython(copy_diff_to_compressed_diff, undo_diff_copy),
    ]
