# Generated by Django 3.2.16 on 2023-05-23 20:05

from django.db import migrations
import nautobot_ssot.models


def copy_diff_to_compressed_diff(apps, schema_editor):
    for sync in nautobot_ssot.models.Sync.objects.all():
        sync.compressed_diff = sync.diff
        sync.validated_save()


def undo_diff_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0005_sync_compressed_diff"),
    ]

    operations = [
        migrations.RunPython(copy_diff_to_compressed_diff, undo_diff_copy),
    ]
