# Generated by Django 3.2.16 on 2023-05-23 20:05
import json

from django.db import connection, migrations

import nautobot_ssot.models


def copy_json_diff_to_diff(apps, schema_editor):
    for sync in nautobot_ssot.models.Sync.objects.raw("SELECT id,diff,json_diff FROM nautobot_ssot_sync"):
        sync.diff = json.loads(sync.json_diff)
        sync.save()


def copy_diff_to_json_diff(apps, schema_editor):
    for sync in nautobot_ssot.models.Sync.objects.all():
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE nautobot_ssot_sync SET json_diff = %s WHERE id = %s",
                (json.dumps(sync.diff), sync.id),
            )


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0005_sync_compressed_diff"),
    ]

    operations = [
        migrations.RunPython(copy_json_diff_to_diff, copy_diff_to_json_diff),
    ]
