# Generated by Django 3.2.16 on 2023-06-14 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0006_copy_diff_to_compressed_diff"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE nautobot_ssot_sync DROP COLUMN json_diff",
                    reverse_sql=[
                        "ALTER TABLE nautobot_ssot_sync ADD COLUMN json_diff JSONB",
                        "UPDATE nautobot_ssot_sync SET json_diff = '{}'",
                        "ALTER TABLE nautobot_ssot_sync ALTER COLUMN json_diff SET NOT NULL",
                    ],
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="sync",
                    name="json_diff",
                ),
            ],
        ),
    ]
