# Generated by Django 3.2.25 on 2024-06-21 17:45

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0106_populate_default_statuses_and_roles_for_contact_associations'),
        ('dcim', '0058_controller_data_migration'),
        ('ipam', '0046_update_all_charfields_max_length_to_255'),
        ('tenancy', '0009_update_all_charfields_max_length_to_255'),
        ('nautobot_ssot', '0008_auto_20240110_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACIAppProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_appprofiles', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'ACI Application Profile',
                'verbose_name_plural': 'ACI Application Profiles',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='ACIBridgeDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_addresses', models.ManyToManyField(blank=True, related_name='aci_bridgedomains', to='ipam.IPAddress')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_bridgedomains', to='tenancy.tenant')),
                ('vrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_bridgedomains', to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'ACI Bridge Domain',
                'verbose_name_plural': 'ACI Bridge Domains',
                'ordering': ['name'],
                'unique_together': {('vrf', 'name', 'tenant')},
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='ACIEPG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_epgs', to='nautobot_ssot.aciappprofile')),
                ('bridge_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_epgs', to='nautobot_ssot.acibridgedomain')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_epgs', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'ACI EPG',
                'verbose_name_plural': 'ACI EPGs',
                'ordering': ['name'],
                'unique_together': {('name', 'application', 'tenant')},
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='ACIAppTermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('epg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_apptermination', to='nautobot_ssot.aciepg')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aci_apptermination', to='dcim.interface')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aci_apptermination', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'ACI App Termination',
                'verbose_name_plural': 'ACI App Termination',
                'ordering': ['name'],
                'unique_together': {('epg', 'interface', 'vlan')},
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
