# Generated by Django 3.2.25 on 2024-08-08 16:44

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models

import nautobot_ssot.integrations.vsphere.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0106_populate_default_statuses_and_roles_for_contact_associations"),
        ("nautobot_ssot", "0010_automationgatewaymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOTvSphereConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enable_sync_to_nautobot", models.BooleanField(default=True)),
                (
                    "default_vm_status_map",
                    models.JSONField(
                        default=nautobot_ssot.integrations.vsphere.models._get_default_vm_status_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "default_ip_status_map",
                    models.JSONField(
                        blank=True,
                        default=nautobot_ssot.integrations.vsphere.models._get_default_ip_status_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "default_vm_interface_map",
                    models.JSONField(
                        blank=True,
                        default=nautobot_ssot.integrations.vsphere.models._get_default_vm_interface_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("primary_ip_sort_by", models.CharField(default="lowest", max_length=255)),
                ("default_ignore_link_local", models.BooleanField(default=True)),
                ("job_enabled", models.BooleanField(default=False)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "vsphere_instance",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="extras.externalintegration"),
                ),
            ],
            options={
                "verbose_name": "SSOT vSphere Config",
                "verbose_name_plural": "SSOT vSphere Configs",
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
    ]
