# Generated by Django 4.2.20 on 2025-03-18 11:32

import django.core.serializers.json
from django.db import migrations, models

import nautobot_ssot.integrations.infoblox.models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0011_alter_sync_job_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssotinfobloxconfig",
            name="infoblox_network_view_to_namespace_map",
            field=models.JSONField(
                default=nautobot_ssot.integrations.infoblox.models._get_network_view_to_namespace_map,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
