# Generated by Django 4.2.20 on 2025-03-13 21:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0011_alter_sync_job_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssotinfobloxconfig",
            name="infoblox_network_view_to_namespace_map",
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
