# Generated by Django 4.2.20 on 2025-03-24 22:42

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_add_graphqlquery_owner_content_type'),
        ('nautobot_ssot', '0011_alter_sync_job_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOTCradlepointConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('job_enabled', models.BooleanField(default=False)),
                ('unique_cradlepoint_field_order', models.CharField(blank=True, max_length=255)),
                ('cradlepoint_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extras.externalintegration')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SSoT Cradlepoint Config',
                'verbose_name_plural': 'SSoT Cradlepoint Configs',
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
