# Generated by Django 4.2.18 on 2025-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_ssot', '0012_ssotvsphereconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssotvsphereconfig',
            name='use_clusters',
            field=models.BooleanField(default=True),
        ),
    ]
