# Generated by Django 4.2.18 on 2025-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_ssot', '0013_ssotvsphereconfig_use_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssotvsphereconfig',
            name='sync_tagged_only',
            field=models.BooleanField(default=True),
        ),
    ]
