# Generated by Django 4.2.24 on 2025-09-26 14:53

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0128_remove_job_approval_required_and_more"),
        ("nautobot_ssot", "0015_ssotvsphereconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source", models.CharField(max_length=255)),
                ("target", models.CharField(max_length=255)),
                ("kwargs", models.JSONField(blank=True, null=True)),
                ("flags", models.BinaryField(blank=True)),
                ("obj_type", models.CharField(max_length=255)),
                ("obj_name", models.CharField(max_length=255)),
                ("obj_keys", models.JSONField(blank=True, null=True)),
                ("source_attrs", models.JSONField(blank=True, null=True)),
                ("target_attrs", models.JSONField(blank=True, null=True)),
                ("action", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                ("synced_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "children",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_records",
                        related_query_name="parent_record",
                        to="nautobot_ssot.syncrecord",
                    ),
                ),
                (
                    "sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        related_query_name="record",
                        to="nautobot_ssot.sync",
                    ),
                ),
                (
                    "synced_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("source", "target", "synced_object_type", "synced_object_id")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
