# Generated by Django 4.2.25 on 2025-10-20 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0015_ssotvsphereconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sync",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Data Sync",
                "verbose_name_plural": "SSoT Sync History",
            },
        ),
    ]
