# Generated by Django 4.2.25 on 2025-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0016_alter_sync_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssotvsphereconfig",
            name="sync_vsphere_tags",
            field=models.BooleanField(default=True),
        ),
    ]
