# Generated by Django 4.2.25 on 2025-10-29 20:32

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nautobot_ssot", "0016_alter_sync_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source", models.CharField(max_length=255)),
                ("target", models.CharField(max_length=255)),
                ("source_kwargs", models.JSONField(blank=True, default=dict)),
                ("target_kwargs", models.JSONField(blank=True, default=dict)),
                ("diffsync_flags", django_enum.fields.SmallIntegerFlagField(blank=True, default=None, null=True)),
                ("obj_type", models.CharField(max_length=255)),
                ("obj_name", models.CharField(max_length=255)),
                ("obj_keys", models.JSONField(blank=True, null=True)),
                ("source_attrs", models.JSONField(blank=True, null=True)),
                ("target_attrs", models.JSONField(blank=True, null=True)),
                ("action", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                ("synced_object_id", models.UUIDField(blank=True, null=True)),
                ("message", models.TextField(blank=True, max_length=1024)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        related_query_name="children",
                        to="nautobot_ssot.syncrecord",
                    ),
                ),
                (
                    "sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        related_query_name="record",
                        to="nautobot_ssot.sync",
                    ),
                ),
                (
                    "synced_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="syncrecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("diffsync_flags__gte", 0), ("diffsync_flags__lte", 15)),
                    ("diffsync_flags", 0),
                    ("diffsync_flags__isnull", True),
                    _connector="OR",
                ),
                name="nautobot_ssot_SyncRecord_diffsync_flags_DiffSyncFlags",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncrecord",
            unique_together={("sync", "obj_name", "obj_type")},
        ),
    ]
