# Generated by Django 4.2.30 on 2026-04-15 18:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("nautobot_ssot", "0017_ssotvsphereconfig_sync_vsphere_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualDeviceContextToControllerManagedDeviceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "controller_managed_device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dcim.controllermanageddevicegroup"
                    ),
                ),
                (
                    "virtual_device_context",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.virtualdevicecontext"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
