# Generated by Django 5.2.15 on 2026-06-29 22:13

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models

import nautobot_ssot.integrations.proxmox.models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_ssot", "0017_ssotvsphereconfig_sync_vsphere_tags"),
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOTProxmoxConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enable_sync_to_nautobot", models.BooleanField(default=True)),
                ("use_clusters", models.BooleanField(default=True)),
                ("sync_lxc", models.BooleanField(default=True)),
                ("sync_nodes_as_devices", models.BooleanField(default=True)),
                ("sync_proxmox_tags", models.BooleanField(default=True)),
                (
                    "default_ssot_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="extras.tag",
                    ),
                ),
                (
                    "default_vm_status_map",
                    models.JSONField(
                        default=nautobot_ssot.integrations.proxmox.models._get_default_vm_status_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "default_ip_status_map",
                    models.JSONField(
                        blank=True,
                        default=nautobot_ssot.integrations.proxmox.models._get_default_ip_status_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "default_node_interface_type_map",
                    models.JSONField(
                        blank=True,
                        default=nautobot_ssot.integrations.proxmox.models._get_default_node_interface_type_map,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("primary_ip_sort_by", models.CharField(default="Lowest", max_length=255)),
                ("default_ignore_link_local", models.BooleanField(default=True)),
                ("job_enabled", models.BooleanField(default=False)),
                (
                    "default_clustergroup_name",
                    models.CharField(default="Proxmox VE Default Cluster Group", max_length=255),
                ),
                ("default_cluster_name", models.CharField(default="Proxmox VE Default Cluster", max_length=255)),
                (
                    "default_cluster_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtualization.clustertype"),
                ),
                (
                    "default_location",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dcim.location"),
                ),
                (
                    "default_device_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dcim.devicetype"),
                ),
                (
                    "default_device_role",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="extras.role"),
                ),
                (
                    "proxmox_instance",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="extras.externalintegration"),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "SSOT Proxmox VE Config",
                "verbose_name_plural": "SSOT Proxmox VE Configs",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
