# Generated by Django 4.2.29 on 2026-03-30 16:58

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.core.models.tree_queries
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("nautobot_ssot", "0017_ssotvsphereconfig_sync_vsphere_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicalGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=48, unique=True)),
                (
                    "control_plane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_groups",
                        to="dcim.controller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logical Group",
                "verbose_name_plural": "Logical Groups",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
            managers=[
                ("objects", nautobot.core.models.tree_queries.TreeManager()),
            ],
        ),
        migrations.CreateModel(
            name="VirtualSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("system_id", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=48)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vsys", to="dcim.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual System",
                "verbose_name_plural": "Virtual Systems",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VirtualSystemAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("iface", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.interface")),
                (
                    "vsys",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nautobot_ssot.virtualsystem"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="virtualsystem",
            name="interfaces",
            field=models.ManyToManyField(
                related_name="assigned_vsys", through="nautobot_ssot.VirtualSystemAssociation", to="dcim.interface"
            ),
        ),
        migrations.AddField(
            model_name="virtualsystem",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.CreateModel(
            name="LogicalGroupToVirtualSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nautobot_ssot.logicalgroup"),
                ),
                (
                    "vsys",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="nautobot_ssot.virtualsystem"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogicalGroupToDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("device", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.device")),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nautobot_ssot.logicalgroup"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="logicalgroup",
            name="devices",
            field=models.ManyToManyField(
                related_name="logical_group", through="nautobot_ssot.LogicalGroupToDevice", to="dcim.device"
            ),
        ),
        migrations.AddField(
            model_name="logicalgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="nautobot_ssot.logicalgroup",
            ),
        ),
        migrations.AddField(
            model_name="logicalgroup",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="logicalgroup",
            name="virtual_systems",
            field=models.ManyToManyField(
                related_name="logical_group",
                through="nautobot_ssot.LogicalGroupToVirtualSystem",
                to="nautobot_ssot.virtualsystem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="virtualsystem",
            unique_together={("device", "name")},
        ),
    ]
