# Generated by Django 4.2.30 on 2026-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_ssot", "0017_ssotvsphereconfig_sync_vsphere_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssotinfobloxconfig",
            name="infoblox_location_ext_attr",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
