# Generated by Django 4.2.29 on 2026-04-14 19:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("nautobot_ssot", "0018_logicalgroup_virtualsystem_virtualsystemassociation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicalGroupToVirtualDeviceContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nautobot_ssot.logicalgroup"),
                ),
                (
                    "virtual_device_context",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.virtualdevicecontext"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="logicalgroup",
            name="virtual_device_contexts",
            field=models.ManyToManyField(
                related_name="logical_group",
                through="nautobot_ssot.LogicalGroupToVirtualDeviceContext",
                to="dcim.virtualdevicecontext",
            ),
        ),
    ]
