"""Utilities."""

from .nbutils import (
    assign_device_to_virtual_chassis,
    create_interface,
    create_ip,
    create_vlan,
    get_device_role_object,
    get_device_type_object,
    get_location_object,
    get_manufacturer_object,
    get_or_create_device_role_object,
    get_or_create_device_type_object,
    get_or_create_location_object,
    get_or_create_manufacturer_object,
    get_or_create_platform_object,
    get_or_create_status_object,
    get_or_create_tag_object,
    get_or_create_virtual_chassis_object,
    get_platform_object,
    get_syncable_device,
    get_virtual_chassis_object,
)
from .test_utils import clean_slate, json_fixture

__all__ = (
    "assign_device_to_virtual_chassis",
    "create_ip",
    "create_interface",
    "json_fixture",
    "create_vlan",
    "clean_slate",
    "get_or_create_device_role_object",
    "get_device_role_object",
    "get_device_type_object",
    "get_location_object",
    "get_manufacturer_object",
    "get_platform_object",
    "get_or_create_device_type_object",
    "get_or_create_location_object",
    "get_or_create_manufacturer_object",
    "get_or_create_platform_object",
    "get_or_create_status_object",
    "get_or_create_tag_object",
    "get_or_create_virtual_chassis_object",
    "get_virtual_chassis_object",
    "get_syncable_device",
)
