"""Constants for use within Nautobot SSoT for Bootstrap."""

from nautobot_ssot.utils import (
    core_supports_softwareversion,
    validate_dlm_installed,
)

SCOPED_FIELDS_MAPPING = {
    "circuits.circuit": [
        "cid",
        "provider",
        "circuit_type",
        "status",
        "install_date",
        "commit_rate",
        "description",
        "tenant",
        "tags",
    ],
    "circuits.circuittermination": [
        "name",
        "term_side",
        "circuit",
        "location",
        "provider_network",
        "port_speed",
        "upstream_speed",
        "xconnect_id",
        "pp_info",
        "description",
        "tags",
    ],
    "circuits.circuittype": ["name", "description"],
    "extras.computedfield": ["label", "content_type", "template"],
    "extras.contact": ["name", "phone", "email", "address", "teams"],
    "extras.customfield": [
        "label",
        "description",
        "type",
        "grouping",
        "weight",
        "filter_logic",
        "advanced_ui",
        "validation_regex",
        "required",
        "content_types",
        "custom_field_choices",
        "validation_minimum",
        "validation_maximum",
        "validation_regex",
        "default",
    ],
    "extras.dynamicgroup": ["name", "content_type", "filter", "description"],
    "extras.externalintegration": [
        "name",
        "remote_url",
        "timeout",
        "verify_ssl",
        "secrets_group",
        "headers",
        "http_method",
        "ca_file_path",
        "extra_config",
        "tags",
    ],
    "extras.gitrepository": ["name", "remote_url", "branch", "secrets_group", "provided_contents"],
    "extras.graphqlquery": ["name", "query"],
    "dcim.location": [
        "name",
        "location_type",
        "parent",
        "status",
        "facility",
        "asn",
        "time_zone",
        "description",
        "tenant",
        "physical_address",
        "shipping_address",
        "latitude",
        "longitude",
        "contact_name",
        "contact_phone",
        "contact_email",
        "tags",
    ],
    "dcim.locationtype": ["name", "parent", "nestable", "description", "content_types"],
    "dcim.manufacturer": ["name", "description"],
    "ipam.namespace": ["name", "description", "location"],
    "dcim.platform": ["name", "manufacturer", "network_driver", "napalm_driver", "napalm_arguments", "description"],
    "ipam.prefix": [
        "network",
        "namespace",
        "type",
        "status",
        "role",
        "rir",
        "date_allocated",
        "description",
        "vrfs",
        "locations",
        "vlan",
        "tenant",
        "tags",
    ],
    "circuits.provider": ["name", "asn", "account", "portal_url", "noc_contact", "admin_contact", "tags"],
    "circuits.providernetwork": ["name", "provider", "description", "comments", "tags"],
    "ipam.rir": ["name", "is_private", "description"],
    "extras.role": ["name", "weight", "description", "color", "content_types"],
    "extras.scheduledjob": [
        "name",
        "job_model",
        "user",
        "interval",
        "start_time",
        "crontab",
        "job_vars",
        "profile",
        "approval_required",
        "enabled",
        "kwargs",
        "celery_kwargs",
    ],
    "extras.secret": ["name", "provider", "parameters"],
    "extras.secretsgroup": ["name", "secrets"],
    "extras.tag": ["name", "color", "content_types", "description"],
    "extras.team": ["name", "phone", "email", "address", "contacts"],
    "tenancy.tenant": ["name", "description", "tenant_group", "tags"],
    "tenancy.tenantgroup": ["name", "parent", "description"],
    "ipam.vlan": ["name", "vid", "vlan_group", "description", "status", "role", "locations", "tenant", "tags"],
    "ipam.vlangroup": ["name", "location", "description"],
    "ipam.vrf": ["name", "namespace", "rd", "description", "tenant", "tags"],
}

if core_supports_softwareversion():
    SCOPED_FIELDS_MAPPING["dcim.softwareimagefile"] = [
        "software_version",
        "image_file_name",
        "platform",
        "status",
        "image_file_size",
        "device_types",
        "download_url",
        "image_file_checksum",
        "hashing_algorithm",
        "default_image",
        "tags",
    ]
    SCOPED_FIELDS_MAPPING["dcim.softwareversion"] = (
        [
            "version",
            "device_platform",
            "alias",
            "release_date",
            "end_of_support_date",
            "status",
            "long_term_support",
            "pre_release",
            "documentation_url",
            "tags",
        ],
    )
if validate_dlm_installed():
    SCOPED_FIELDS_MAPPING["nautobot_device_lifecycle_mgmt.validatedsoftwarelcm"] = [
        "software",
        "start",
        "end",
        "devices",
        "device_types",
        "device_roles",
        "inventory_items",
        "object_tags",
        "preferred",
        "tags",
        "platform",
        "software_version",
    ]
