"""Constants for use within Nautobot SSoT for Bootstrap."""

from nautobot.circuits.models import Circuit, CircuitTermination, CircuitType, Provider, ProviderNetwork
from nautobot.dcim.models import Location, LocationType, Manufacturer, Platform
from nautobot.extras.models import (
    ComputedField,
    Contact,
    CustomField,
    DynamicGroup,
    GitRepository,
    GraphQLQuery,
    Role,
    ScheduledJob,
    Secret,
    SecretsGroup,
    Tag,
    Team,
)
from nautobot.ipam.models import RIR, VLAN, VRF, Namespace, Prefix, VLANGroup
from nautobot.tenancy.models import Tenant, TenantGroup

from nautobot_ssot.utils import (
    core_supports_softwareversion,
    validate_dlm_installed,
)

SCOPED_FIELDS_MAPPING = {
    Circuit: [
        "cid",
        "provider",
        "circuit_type",
        "status",
        "install_date",
        "commit_rate",
        "description",
        "tenant",
        "tags",
    ],
    CircuitTermination: [
        "name",
        "term_side",
        "circuit",
        "location",
        "provider_network",
        "port_speed",
        "upstream_speed",
        "xconnect_id",
        "pp_info",
        "description",
        "tags",
    ],
    CircuitType: ["name", "description"],
    ComputedField: ["label", "content_type", "template"],
    Contact: ["name", "phone", "email", "address", "teams"],
    CustomField: [
        "label",
        "description",
        "type",
        "grouping",
        "weight",
        "filter_logic",
        "advanced_ui",
        "validation_regex",
        "required",
        "content_types",
        "custom_field_choices",
        "validation_minimum",
        "validation_maximum",
        "validation_regex",
        "default",
    ],
    DynamicGroup: ["name", "content_type", "filter", "description"],
    GitRepository: ["name", "remote_url", "branch", "secrets_group", "provided_contents"],
    GraphQLQuery: ["name", "query"],
    Location: [
        "name",
        "location_type",
        "parent",
        "status",
        "facility",
        "asn",
        "time_zone",
        "description",
        "tenant",
        "physical_address",
        "shipping_address",
        "latitude",
        "longitude",
        "contact_name",
        "contact_phone",
        "contact_email",
        "tags",
    ],
    LocationType: ["name", "parent", "nestable", "description", "content_types"],
    Manufacturer: ["name", "description"],
    Namespace: ["name", "description", "location"],
    Platform: ["name", "manufacturer", "network_driver", "napalm_driver", "napalm_arguments", "description"],
    Prefix: [
        "network",
        "namespace",
        "type",
        "status",
        "role",
        "rir",
        "date_allocated",
        "description",
        "vrfs",
        "locations",
        "vlan",
        "tenant",
        "tags",
    ],
    Provider: ["name", "asn", "account", "portal_url", "noc_contact", "admin_contact", "tags"],
    ProviderNetwork: ["name", "provider", "description", "comments", "tags"],
    RIR: ["name", "is_private", "description"],
    Role: ["name", "weight", "description", "color", "content_types"],
    ScheduledJob: [
        "name",
        "job_model",
        "user",
        "interval",
        "start_time",
        "crontab",
        "job_vars",
        "profile",
        "approval_required",
        "enabled",
        "kwargs",
        "celery_kwargs",
    ],
    Secret: ["name", "provider", "parameters"],
    SecretsGroup: ["name", "secrets"],
    Tag: ["name", "color", "content_types", "description"],
    Team: ["name", "phone", "email", "address", "contacts"],
    Tenant: ["name", "description", "tenant_group", "tags"],
    TenantGroup: ["name", "parent", "description"],
    VLAN: ["name", "vid", "vlan_group", "description", "status", "role", "locations", "tenant", "tags"],
    VLANGroup: ["name", "location", "description"],
    VRF: ["name", "namespace", "rd", "description", "tenant", "tags"],
}

if core_supports_softwareversion():
    from nautobot.dcim.models import SoftwareImageFile, SoftwareVersion  # pylint: disable=ungrouped-imports

    SCOPED_FIELDS_MAPPING[SoftwareImageFile] = [
        "software_version",
        "image_file_name",
        "platform",
        "status",
        "image_file_size",
        "device_types",
        "download_url",
        "image_file_checksum",
        "hashing_algorithm",
        "default_image",
        "tags",
    ]
    SCOPED_FIELDS_MAPPING[SoftwareVersion] = (
        [
            "version",
            "device_platform",
            "alias",
            "release_date",
            "end_of_support_date",
            "status",
            "long_term_support",
            "pre_release",
            "documentation_url",
            "tags",
        ],
    )
if validate_dlm_installed():
    from nautobot_device_lifecycle_mgmt.models import ValidatedSoftwareLCM  # pylint: disable=ungrouped-imports

    SCOPED_FIELDS_MAPPING[ValidatedSoftwareLCM] = [
        "software",
        "start",
        "end",
        "devices",
        "device_types",
        "device_roles",
        "inventory_items",
        "object_tags",
        "preferred",
        "tags",
        "platform",
        "software_version",
    ]
