"""Constants for LibreNMS SSoT."""

from django.conf import settings

# Import config vars from nautobot_config.py
PLUGIN_CFG = settings.PLUGINS_CONFIG["nautobot_ssot"]

librenms_status_map = {  # pylint: disable=W0109
    0: "Offline",
    1: "Active",
    True: "Active",
    False: "Offline",
}

os_manufacturer_map = {
    # Other types
    "ping": "Generic",
    "hpe-ilo": "HP",
    "proxmox": "Proxmox",
    "opnsense": "Opnsense",
    # Types from LibreNMS/OS php files
    "aen": "Accedian OS",
    "airos": "Ubiquiti",
    "airosaf": "Ubiquiti",
    "airosaf60": "Ubiquiti",
    "airosafltu": "Ubiquiti",
    "airport": "Apple",
    "aix": "IBM",
    "alcoma_almp": "Alcoma",
    "alfo80hd": "Siae Microelettronica",
    "allied": "Allied Telesis",
    "allworxvoip": "Allworx",
    "anue": "IXIA",
    "aos": "Alcatel-Lucent",
    "apc": "APC",
    "apexlynx": "Apex",
    "apexplus": "Apex",
    "aprisa": "4RF",
    "apsoluteos": "Radware",
    "arbos": "Aruba Networks",
    "areca": "Areca",
    "arista_eos": "Arista",
    "arrisc4": "Arris",
    "arriscm": "Arris",
    "arrisdsr4410md": "Arris",
    "arubainstant": "Aruba Networks",
    "arubaos": "Aruba Networks",
    "arubaoscx": "Aruba Networks",
    "asa": "Cisco",
    "asuswrtmerlin": "Asus",
    "asyncos": "Cisco",
    "aviatwtm": "Aviat Networks",
    "avocent": "Avocent",
    "awplus": "Allied Telesis",
    "axos": "Calix",
    "baicellsod04": "Baicells",
    "barracudangfirewall": "Barracuda",
    "bats": "BAT",
    "beagleboard": "BeagleBoard",
    "boss": "Beijer Electronics",
    "brother": "Brother",
    "ceraos": "Ceragon",
    "cienarls": "Ciena",
    "cienasds": "Ciena",
    "ciscosb": "Cisco",
    "ciscowlc": "Cisco",
    "cnpilote": "Cambium Networks",
    "comware": "HPE",
    "coriant": "Coriant",
    "cumulus": "Cumulus Networks",
    "cyberpower": "CyberPower",
    "danthermos": "Dantherm",
    "ddwrt": "DD-WRT",
    "deliberant": "Deliberant",
    "delllaser": "Dell",
    "dhcpatriot": "DHCPatriot",
    "dlink": "D-Link",
    "dlinkap": "D-Link",
    "dnos": "Dell EMC",
    "edgecos": "Edgecore",
    "edgeos": "Ubiquiti",
    "edgeosolt": "Ubiquiti",
    "edgeswitch": "Ubiquiti",
    "ekinops": "Ekinops",
    "eltexmes23xx": "Eltex",
    "eltexmes24xx": "Eltex",
    "engenius": "EnGenius",
    "enterasys": "Enterasys",
    "epmp": "Cambium Networks",
    "ericsson6600": "Ericsson",
    "ericssonml": "Ericsson",
    "ericssontn": "Ericsson",
    "eurostor": "Eurostor",
    "ewc": "Extreme Networks",
    "exa": "Exa Networks",
    "extendair": "ExtendAir",
    "extremeware": "Extreme Networks",
    "f5": "F5 Networks",
    "fabos": "Brocade",
    "fortiadc": "Fortinet",
    "fortiap": "Fortinet",
    "fortiextender": "Fortinet",
    "fortigate": "Fortinet",
    "fortios": "Fortinet",
    "fortiwlc": "Fortinet",
    "fscentec": "FS",
    "fsgbn": "FS",
    "fsswitch": "FS",
    "ftos": "Dell EMC",
    "gaia": "Check Point",
    "generic": "Generic",
    "gepulsar": "Ge",
    "harmonyenhanced": "Harmony",
    "helios": "Helios",
    "himoinstags": "Himoinsa",
    "hiveoswireless": "HiveOS",
    "horizoncompact": "Dragonwave",
    "horizoncompactplus": "Dragonwave",
    "horizonduo": "Dragonwave",
    "hpmsm": "HP",
    "hpvc": "HP",
    "icros": "Advantech",
    "ifotec": "Ifotec",
    "infineragroove": "Infinera",
    "infinity": "Infinity",
    "ios": "Cisco",
    "iosxe": "Cisco",
    "iosxr": "Cisco",
    "ipolis": "Samsung",
    "ird": "IRD",
    "ironware": "Brocade",
    "jetdirect": "HP",
    "junos": "Juniper",
    "junose": "Juniper",
    "lcos": "Lancom",
    "lcoslx": "Lancom",
    "lcossx": "Lancom",
    "linux": "Linux",
    "mimosa": "Mimosa Networks",
    "mni": "MNI",
    "moxaetherdevice": "Moxa",
    "mrvod": "MRV",
    "netscaler": "Citrix",
    "netsure": "NetSure",
    "nios": "Infoblox",
    "nitro": "Citrix",
    "nsbsd": "BSD",
    "nxos": "Cisco",
    "ocnos": "OcNOS",
    "okilan": "Oki",
    "openbsd": "BSD",
    "openwrt": "OpenWrt",
    "packetlight": "PacketLight",
    "panos": "Palo Alto",
    "pbn": "PBN",
    "pbncp": "PBN",
    "pepwave": "Peplink",
    "pfsense": "PfSense",
    "pmp": "Cambium Networks",
    "poweralert": "APC",
    "powerconnect": "Dell EMC",
    "procurve": "HPE",
    "procera": "AppLogic",
    "protelevisiont1": "ProTelevision",
    "ptp250": "Cambium Networks",
    "ptp500": "Cambium Networks",
    "ptp600": "Cambium Networks",
    "ptp650": "Cambium Networks",
    "ptp670": "Cambium Networks",
    "ptp800": "Cambium Networks",
    "pulse": "PulseSecure",
    "qnap": "QNAP",
    "quanta": "Quanta",
    "quantastor": "QuantaStor",
    "radlan": "Radlan",
    "radwin": "Radwin",
    "ray": "Racom",
    "ray3": "Racom",
    "riverbed": "Riverbed",
    "routeros": "Mikrotik",
    "ruckuswireless": "Ruckus",
    "ruckuswirelesshotzone": "Ruckus",
    "ruckuswirelesssz": "Ruckus",
    "ruckuswirelessunleashed": "Ruckus",
    "rutos2xx": "Teltonika",
    "rutosrutx": "Teltonika",
    "saf": "Saf Tehnika",
    "safcfm": "Saf Tehnika",
    "safintegrab": "Saf Tehnika",
    "safintegrae": "Saf Tehnika",
    "safintegraw": "Saf Tehnika",
    "safintegrax": "Saf Tehnika",
    "scalance": "Siemens",
    "schleifenbauer": "Schleifenbauer",
    "screenos": "Juniper",
    "secureplatform": "Check Point",
    "serveriron": "Brocade",
    "sgos": "Symantec",
    "siklu": "Siklu",
    "siteboss": "SiteBoss",
    "siteboss550": "SiteBoss",
    "smos": "Microchip",
    "smartax": "Huawei",
    "smartaxmdu": "Huawei",
    "socomecups": "Socomec",
    "sonicwall": "SonicWall",
    "speedtouch": "Thomson",
    "stellar": "Stellar",
    "supermicrobmc": "Supermicro",
    "svos": "Supermicro",
    "symbol": "Symbol",
    "tachyon": "Tachyon Networks",
    "taitinfra93": "Tait",
    "teldat": "Teldat",
    "terra": "Terra",
    "threecom": "3Com",
    "timos": "Nokia",
    "topvision": "TopVision",
    "ucos": "UC-OS",
    "unifi": "Ubiquiti",
    "valere": "Valere",
    "viptela": "Cisco",
    "vmwareesxi": "VMware",
    "vrp": "Huawei",
    "windows": "Microsoft",
    "xerox": "Xerox",
    "xirrusaos": "Xirrus",
    "xos": "Extreme Networks",
    "zebra": "Zebra",
    "zxdsl": "ZTE",
    "zynos": "Zyxel",
    "zywall": "Zyxel",
    "zyxelnwa": "Zyxel",
    "zyxelwlc": "Zyxel",
}

manufacturer_os_map = {
    # Other Types
    "Proxmox": ["proxmox"],
    "Generic": ["generic", "ping"],
    "Opnsense": ["opnsense"],
    # Types imported from LibreNMS/OS php files
    "4RF": ["aprisa"],
    "3Com": ["threecom"],
    "Accedian OS": ["aen"],
    "Advantech": ["icros"],
    "Alcatel-Lucent": ["aos"],
    "Alcoma": ["alcoma_almp"],
    "Allied Telesis": ["allied", "awplus"],
    "Allworx": ["allworxvoip"],
    "APC": ["apc", "poweralert"],
    "Apple": ["airport"],
    "AppLogic": ["procera"],
    "Aruba Networks": ["arbos", "arubainstant", "arubaos", "arubaoscx"],
    "Areca": ["areca"],
    "Arris": ["arrisc4", "arriscm", "arrisdsr4410md"],
    "BAT": ["bats"],
    "Baicells": ["baicellsod04"],
    "Barracuda": ["barracudangfirewall"],
    "BeagleBoard": ["beagleboard"],
    "Beijer Electronics": ["boss"],
    "Brother": ["brother"],
    "Brocade": ["fabos", "ironware", "serveriron"],
    "BSD": ["nsbsd", "openbsd"],
    "Cambium Networks": [
        "epmp",
        "pmp",
        "ptp250",
        "ptp500",
        "ptp600",
        "ptp650",
        "ptp670",
        "ptp800",
    ],
    "Calix": ["axos"],
    "Ceragon": ["ceraos"],
    "Check Point": ["gaia", "secureplatform"],
    "Ciena": ["cienarls", "cienasds"],
    "Citrix": ["netscaler", "nitro"],
    "Cisco": [
        "asa",
        "asyncos",
        "ciscosb",
        "ciscowlc",
        "fortigate",
        "ios",
        "iosxe",
        "iosxr",
        "viptela",
    ],
    "Cyberpower": ["cyberpower"],
    "D-Link": ["dlink", "dlinkap"],
    "Dantherm": ["danthermos"],
    "DD-WRT": ["ddwrt"],
    "Dell": ["delllaser"],
    "Dell EMC": ["dnos", "powerconnect", "ftos"],
    "Dragonwave": ["horizoncompact", "horizoncompactplus", "horizonduo"],
    "Eltex": ["eltexmes23xx", "eltexmes24xx"],
    "EnGenius": ["engenius"],
    "Enterasys": ["enterasys"],
    "Ericsson": ["ericsson6600", "ericssonml", "ericssontn"],
    "Ekinops": ["ekinops"],
    "Eurostor": ["eurostor"],
    "Extreme Networks": ["extremeware", "ewc", "xos"],
    "Exa Networks": ["exa"],
    "FS": ["fscentec", "fsgbn", "fsswitch"],
    "F5 Networks": ["f5"],
    "Fortinet": [
        "fortiadc",
        "fortiap",
        "fortiextender",
        "fortigate",
        "fortios",
        "fortiwlc",
    ],
    "Ge": ["gepulsar"],
    "Harmony": ["harmonyenhanced"],
    "Helios": ["helios"],
    "Himoinsa": ["himoinstags"],
    "HPE": ["comware", "procurve"],
    "Huawei": ["smartax", "smartaxmdu", "vrp"],
    "IBM": ["aix"],
    "Infinera": ["infineragroove"],
    "Infinity": ["infinity"],
    "Juniper": ["junos", "junose", "screenos"],
    "Lancom": ["lcos", "lcoslx", "lcossx"],
    "Linux": ["linux"],
    "Mikrotik": ["routeros"],
    "Mimosa Networks": ["mimosa"],
    "Microsoft": ["windows"],
    "MRV": ["mrvod"],
    "NetSure": ["netsure"],
    "Nokia": ["timos"],
    "OpenWrt": ["openwrt"],
    "PacketLight": ["packetlight"],
    "Palo Alto": ["panos"],
    "Peplink": ["pepwave"],
    "PfSense": ["pfsense"],
    "PulseSecure": ["pulse"],
    "QNAP": ["qnap"],
    "Quanta": ["quanta"],
    "QuantaStor": ["quantastor"],
    "Racom": ["ray", "ray3"],
    "Radlan": ["radlan"],
    "Radwin": ["radwin"],
    "Ruckus": [
        "ruckuswireless",
        "ruckuswirelesshotzone",
        "ruckuswirelesssz",
        "ruckuswirelessunleashed",
    ],
    "Saf Tehnika": [
        "saf",
        "safcfm",
        "safintegrab",
        "safintegrae",
        "safintegraw",
        "safintegrax",
    ],
    "Samsung": ["ipolis"],
    "Schleifenbauer": ["schleifenbauer"],
    "Siemens": ["scalance"],
    "SiteBoss": ["siteboss", "siteboss550"],
    "Supermicro": ["supermicrobmc", "svos"],
    "Symbol": ["symbol"],
    "Tachyon Networks": ["tachyon"],
    "Teltonika": ["rutos2xx", "rutosrutx"],
    "Terra": ["terra"],
    "Thomson": ["speedtouch"],
    "Ubiquiti": [
        "airos",
        "airosaf",
        "airosaf60",
        "airosafltu",
        "edgeos",
        "edgeosolt",
        "edgeswitch",
        "unifi",
    ],
    "VMware": ["vmwareesxi"],
    "Xirrus": ["xirrusaos"],
    "Xerox": ["xerox"],
    "Zebra": ["zebra"],
    "ZTE": ["zxdsl"],
    "Zyxel": ["zynos", "zywall", "zyxelnwa", "zyxelwlc"],
}

# LibreNMS | Normalized
LIBRENMS_LIB_MAPPER = {
    "arista_eos": "arista_eos",
    "ios": "cisco_ios",
    "iosxe": "cisco_xe",
    "iosxr": "cisco_xr",
    "nxos": "cisco_nxos",
    "junos": "juniper_junos",
    "procera": "applogic_procera",
}

# Normalized | LibreNMS
LIBRENMS_LIB_MAPPER_REVERSE = {
    "arista_eos": "arista_eos",
    "cisco_ios": "ios",
    "cisco_xe": "iosxe",
    "cisco_nxos": "nxos",
    "cisco_xr": "iosxr",
    "juniper_junos": "junos",
    "applogic_procera": "procera",
}

# LibreNMS `os` | network driver
# Separate from LIBRENMS_LIB_MAPPER, which also drives legacy naming: an entry there would
# rename platforms (fortios -> fortinet.fortios.fortios) and move devices.
# Values are MAIN_LIB_MAPPER keys, except applogic_procera (legacy, kept for compatibility).
# Ambiguous OS values (dnos, asyncos, junose, extremeware, zynos, zywall, sonicwall, pfsense,
# opnsense, vmwareesxi, aix, cumulus, axos) intentionally absent -> "". Map them via
# librenms_network_driver_map.
LIBRENMS_OS_TO_NETWORK_DRIVER = {
    # Cisco
    "ios": "cisco_ios",
    "iosxe": "cisco_xe",
    "iosxr": "cisco_xr",
    "nxos": "cisco_nxos",
    "asa": "cisco_asa",
    "ciscosb": "cisco_s300",
    "ciscowlc": "cisco_wlc",
    "viptela": "cisco_viptella",
    # Juniper
    "junos": "juniper_junos",
    "screenos": "juniper_screenos",
    # Arista
    "arista_eos": "arista_eos",
    # Aruba
    "arubaoscx": "aruba_aoscx",
    "arubaos": "aruba_os",
    "arubainstant": "aruba_os",
    # HP
    "procurve": "hp_procurve",
    "comware": "hp_comware",
    # Fortinet
    "fortigate": "fortinet",
    "fortios": "fortinet",
    # Palo Alto
    "panos": "paloalto_panos",
    # Check Point
    "gaia": "checkpoint_gaia",
    # F5
    "f5": "bigip_f5",
    # Mikrotik
    "routeros": "mikrotik_routeros",
    # Huawei
    "vrp": "huawei_vrp",
    "smartax": "huawei_smartax",
    "smartaxmdu": "huawei_smartax",
    # Nokia
    "timos": "nokia_sros",
    # Alcatel
    "aos": "alcatel_aos",
    # Extreme
    "xos": "extreme_exos",
    # Brocade
    "fabos": "brocade_fos",
    "ironware": "brocade_netiron",
    # Dell
    "ftos": "dell_force10",
    "powerconnect": "dell_powerconnect",
    # Ubiquiti
    "airos": "ubiquiti_airos",
    "edgeos": "ubiquiti_edgerouter",
    "edgeswitch": "ubiquiti_edgeswitch",
    "unifi": "ubiquiti_unifiswitch",
    # Ciena
    "cienarls": "ciena_saos",
    "cienasds": "ciena_saos",
    # IP Infusion
    "ocnos": "ipinfusion_ocnos",
    # Eltex
    "eltexmes23xx": "eltex",
    "eltexmes24xx": "eltex",
    # Allied Telesis
    "awplus": "allied_telesis_awplus",
    # Ruckus
    "ruckuswirelesssz": "ruckus_smartzone",
    # Citrix
    "nitro": "netscaler",
    # AppLogic -- not a netutils driver; LIBRENMS_LIB_MAPPER has always emitted it
    "procera": "applogic_procera",
    # Self-mappings: keep f(f(os)) == f(os); consolidated mode re-resolves driver-space values
    "alcatel_aos": "alcatel_aos",
    "allied_telesis_awplus": "allied_telesis_awplus",
    "applogic_procera": "applogic_procera",
    "aruba_aoscx": "aruba_aoscx",
    "aruba_os": "aruba_os",
    "bigip_f5": "bigip_f5",
    "brocade_fos": "brocade_fos",
    "brocade_netiron": "brocade_netiron",
    "checkpoint_gaia": "checkpoint_gaia",
    "ciena_saos": "ciena_saos",
    "cisco_asa": "cisco_asa",
    "cisco_ios": "cisco_ios",
    "cisco_nxos": "cisco_nxos",
    "cisco_s300": "cisco_s300",
    "cisco_viptella": "cisco_viptella",
    "cisco_wlc": "cisco_wlc",
    "cisco_xe": "cisco_xe",
    "cisco_xr": "cisco_xr",
    "dell_force10": "dell_force10",
    "dell_powerconnect": "dell_powerconnect",
    "eltex": "eltex",
    "extreme_exos": "extreme_exos",
    "fortinet": "fortinet",
    "hp_comware": "hp_comware",
    "hp_procurve": "hp_procurve",
    "huawei_smartax": "huawei_smartax",
    "huawei_vrp": "huawei_vrp",
    "ipinfusion_ocnos": "ipinfusion_ocnos",
    "juniper_junos": "juniper_junos",
    "juniper_screenos": "juniper_screenos",
    "mikrotik_routeros": "mikrotik_routeros",
    "netscaler": "netscaler",
    "nokia_sros": "nokia_sros",
    "paloalto_panos": "paloalto_panos",
    "ruckus_smartzone": "ruckus_smartzone",
    "ubiquiti_airos": "ubiquiti_airos",
    "ubiquiti_edgerouter": "ubiquiti_edgerouter",
    "ubiquiti_edgeswitch": "ubiquiti_edgeswitch",
    "ubiquiti_unifiswitch": "ubiquiti_unifiswitch",
}
