"""Constants used by IPFabric Integration."""

ALLOW_DUPLICATE_ADDRESSES = True
DEFAULT_DEVICE_ROLE = "Network Device"
DEFAULT_DEVICE_ROLE_COLOR = "ff0000"
DEFAULT_DEVICE_STATUS = "Active"
DEFAULT_DEVICE_STATUS_COLOR = "ff0000"
DEFAULT_INTERFACE_MAC = "00:00:00:00:00:01"
DEFAULT_INTERFACE_MTU = 1500
DEFAULT_INTERFACE_TYPE = "1000base-t"
SAFE_DELETE_DEVICE_STATUS = "Deprecated"
SAFE_DELETE_IPADDRESS_STATUS = "Deprecated"
SAFE_DELETE_SITE_STATUS = "Decommissioning"
SAFE_DELETE_VLAN_STATUS = "Inventory"
SAFE_IPADDRESS_INTERFACES_STATUS = "Deprecated"
