# Generated by Django 3.1.12 on 2021-12-21 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0018_joblog_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOTServiceNowConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("servicenow_instance", models.CharField(blank=True, max_length=100)),
                (
                    "servicenow_secrets",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.secretsgroup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
